version: '2'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    image: wordpress:4.9.8-php7.2-fpm-alpine
    depends_on:
      - db
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - tmp/mysql:/var/lib/mysql
