version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - wordpress
    ports:
      - "10080:80"
    volumes:
      - ./tmp/html:/var/www/html
      - ./tmp/nginx:/var/log/nginx
  wordpress:
    image: wordpress:php7.3-fpm
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./tmp/html:/var/www/html
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
